'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5662
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PDAEPI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend ReadOnly Property BeginningOfQuestionnaire() As String
            Get
                Return ResourceManager.GetString("BeginningOfQuestionnaire", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Source = \Program Files\PDAEPI\PDAEPI.sdf; password = &apos;password&apos;.
        '''</summary>
        Friend ReadOnly Property connectionString() As String
            Get
                Return ResourceManager.GetString("connectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Districts.
        '''</summary>
        Friend ReadOnly Property DistrictsTable() As String
            Get
                Return ResourceManager.GetString("DistrictsTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -1.
        '''</summary>
        Friend ReadOnly Property EndOfQuestionnaire() As String
            Get
                Return ResourceManager.GetString("EndOfQuestionnaire", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provinces.
        '''</summary>
        Friend ReadOnly Property ProvincesTable() As String
            Get
                Return ResourceManager.GetString("ProvincesTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QTables.
        '''</summary>
        Friend ReadOnly Property QTablesTable() As String
            Get
                Return ResourceManager.GetString("QTablesTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QuestionnaireSections.
        '''</summary>
        Friend ReadOnly Property QuestionnaireSections() As String
            Get
                Return ResourceManager.GetString("QuestionnaireSections", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SubSections.
        '''</summary>
        Friend ReadOnly Property QuestionnaireSubsections() As String
            Get
                Return ResourceManager.GetString("QuestionnaireSubsections", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Questionnaire.
        '''</summary>
        Friend ReadOnly Property QuestionsTable() As String
            Get
                Return ResourceManager.GetString("QuestionsTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QuestionResponses.
        '''</summary>
        Friend ReadOnly Property ResponsesTable() As String
            Get
                Return ResourceManager.GetString("ResponsesTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sites.
        '''</summary>
        Friend ReadOnly Property SitesTable() As String
            Get
                Return ResourceManager.GetString("SitesTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SkipSequence.
        '''</summary>
        Friend ReadOnly Property SkipsTable() As String
            Get
                Return ResourceManager.GetString("SkipsTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Study.
        '''</summary>
        Friend ReadOnly Property StudyTable() As String
            Get
                Return ResourceManager.GetString("StudyTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TableFieldMapping.
        '''</summary>
        Friend ReadOnly Property TableFieldMappingTable() As String
            Get
                Return ResourceManager.GetString("TableFieldMappingTable", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
